### ISSUE TITLE
RFC4122 accordance

### ISSUE THREAD

**Issue by vporoshok** [Rawieo/random.js#1]
It would be pretty if uuid method will return valid uuid v4 https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29

**Comment by Rawieo** [comment]
I guess I've [fixed](https://github.com/Rawieo/random.js/commit/ff43c77cf6dbdc7804510feb2c33e1127e605102) it

**Comment by vporoshok** [comment]
so quick…
>  `xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx` where `x` is any hexadecimal digit and `y` is one of `8`, `9`, `A`, or `B` (e.g., f47ac10b-58cc-4372-**a**567-0e02b2c3d479)

`y` is one of `8`, `9`, `A`, or `B`
